unstable_features = true

max_width = 240
short_array_element_width_threshold = 40
single_line_if_else_max_width = 80
struct_field_align_threshold = 60
struct_lit_single_line = true
struct_lit_width = 30
tab_spaces = 4
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
combine_control_expr = true
empty_item_single_line = true
merge_derives = true
fn_args_layout = "Compressed"
fn_call_width = 100
fn_single_line = true
force_explicit_abi = true
format_strings = true
indent_style = "Block"
#indent_style = "Visual"
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
imports_granularity = "Module"
reorder_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
reorder_modules = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
trailing_comma = "Never"
trailing_semicolon = true
use_field_init_shorthand = true
type_punctuation_density = "Wide"
control_brace_style = "AlwaysSameLine"
brace_style= "SameLineWhere"
where_single_line = true
wrap_comments = true
binop_separator = "Front"
format_macro_matchers = true
format_code_in_doc_comments = true